#!/usr/bin/env python3

numbers = [1,2,3,4,5]

for i in numbers:
  square = i ** 2
  print("Square of ", i, "is", square)
# END

numbers = [1,2,3,4,5]
s = 0

for i in numbers:
  s = s + i
listSize = len(numbers)
average = s / listsize
print(average)
# END

for i in range(1,11):
  if i % 2 == 0:
    print('even number:',i)
  else:
    print('odd number',i)
