#!/usr/bin/env python3

numbers = [1,2,3,4,5]

for i in numbers:
  square = i ** 2
  print("Square of ", i, "is", square)
# END

numbers = [1,2,3,4,5]
s = 0

for i in numbers:
  s = s + i
listSize = len(numbers)
average = s / listsize
print(average)
# END

for i in range(1,11):
  if i % 2 == 0:
    print('even number:',i)
  else:
    print('odd number',i)
# END

numbers = [1,2,3,4,5]

size = len(numbers)
for i in range(size):
    print(numbers[i])
# END

first = [2,4,6]
second = [2,4,6]

for i in first:
    for i in second:
      if i == j:
        continue
      print(i, '*', j, '= ', i*j)
# continue means go back to the start for another thing, END

first = [2,3,4]
second = [20,30,40]

final = []

for i in first:
  for j in second:
    final.append(i+j)
print(final)
# END

def makedeck():
  deck = []
  suits = ['\u2660','\u2665','\u2666','\u2663']
  ranks = ['A',2,3,4,5,6,7,8,9,10,'J','Q','K']
  for suit in suits:
    for rank in ranks:
      deck.append('{}{}'.format(rank,suit))
  print(deck)
  
makedeck()
# END
