#!/usr/bin/env python3

def q1(floatstr):
    '''
    TLO: 112-SCRPY002, LSA 3,4
    Given the floatstr, which is a comma separated string of
    floats, return a list with each of the floats in the 
    argument as elements in the list.
    '''
    newList = []
    for y in floatstr.split(','):
        newList.append(float(y))
    return newList

    pass
    
#return [float(x) for x in float.split(',')]
#return list(map(float,floatstr.split(',')))

def q2(*args):
    '''
    TLO: 112-SCRPY006, LSA 3
    TLO: 112-SCRPY007, LSA 4
    Given the variable length argument list, return the average
    of all the arguments as a float
    '''
    s = 0
    for arg in args:
        s += arg
    return s/len(args)
    #return [float((sum('args')) / len(str(args.split(' '))))]

    pass

def q3(lst,n):
    '''
    TLO: 112-SCRPY004, LSA 3
    Given a list (lst) and a number of items (n), return a new 
    list containing the last n entries in lst.
    '''
   return lst[-n:]
    pass

def q4(strng):
    '''
    TLO: 112-SCRPY004, LSA 1,2
    TLO: 112-SCRPY006, LSA 3
    Given an input string, return a list containing the ordinal numbers of 
    each character in the string in the order found in the input string.
    '''
    '''new_list = []
    for i in strng:
        new_list.append(ord(i))
    return new_list'''
    ordNum = []
    for i in strng:
        ordNum.append(ord(i))
    return ordNum
    #return [ord(x) for x in list(strng)]
    pass

def q5(strng):
    '''
    TLO: 112-SCRPY002, LSA 1,3
    TLO: 112-SCRPY004, LSA 2
    Given an input string, return a tuple with each element in the tuple
    containing a single word from the input string in order.
    '''
    '''t = []
    stri = strng.split(' ')
    for g in strng:
        t.append(g)
    return tuple(t)'''
    return tuple(strng.split())
    pass




